name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@af9aaf53d1ae2230cb82617c563c9427a22a8c15 # v1.66.0
        with:
          shell: release

      - name: Release to GitHub
        run: |
          set -euo pipefail
          gh release create "${TAG}" --repo "${REPOSITORY}" --title "${TAG}" --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          TAG: ${{ github.ref_name }}
